// js/local/dialog/lines.js - What she says (the line banks).
// A bank maps a key to lines; "|" splits a line into separate bubbles. Keys, most specific first:
//     "<intent>@<stage>"   only at that stage (stranger / acquaintance / curious / crush)
//     "<intent>@warm"      curious or crush        "<intent>@cold"   stranger or acquaintance
//     "<intent>"           any stage
// Her voice bank (persona.voice_type) is looked at first, then "shared". mood.neg / sad / low are used
// when she's irritated / sad / tired or drained. Write lines normally (capitals, punctuation): the
// Texting Style Engine turns them into her texting (lowercase, abbreviations, her laugh...).
// Fill-ins: {name} his name, {self} her name, {age} {city} {district} {job} {like} {like2} {hobby}
// {hobby2} {pet} {family} {doing} {x} (the thing being talked about), {cardbit} (from his card).
window.SL = window.SL || {};
SL.dialog = SL.dialog || {};

SL.dialog.LINES = {
    shared: {
        greet: ["Hey!", "Hii", "Hey you", "Hello hello", "Hey :)", "Hi!"],
        "greet@warm": ["Heyy you", "There you are", "Hii, I was hoping you'd text"],
        greet_again: ["Hi again haha", "We already said hi lol", "Hey again"],
        greet_late: ["Hey! What are you doing up so late?", "Hi, night owl", "Hey. Can't sleep either?"],
        greet_morning: ["Morning!", "Good morning!", "Morning :) you're up early"],
        how_are_you: ["I'm good! You?", "Pretty good, kinda tired. You?", "Not bad at all, how about you?", "Good good. What about you?"],
        "how_are_you@warm": ["Better now that you're here haha. You?", "Good! Even better now. You?", "Good, I was waiting for your text. How are you?"],
        answer_good: ["Love that", "Good to hear", "Yay", "Nice, glad you're good", "Good!"],
        answer_bad: ["Oh no, what happened?", "Aw that sucks, wanna talk about it?", "Ugh, I'm sorry. What's wrong?", "Noo, why? What happened?"],
        news_good: ["Yay, what happened?", "Love that! Tell me", "Ooh, why? Tell me everything", "That's amazing, I'm happy for you"],
        "answer_bad@warm": ["Hey, come here. What happened?", "Aw no, I wish I could give you a hug right now. Tell me", "I'm here. Talk to me"],
        morning: ["Good morning!", "Morning :) did you sleep well?", "Morning! Coffee first?"],
        "morning@warm": ["Good morning you", "Morning! Slept well?", "Good morning :) I was hoping you'd text"],
        night: ["Good night! Sleep well", "Night night", "Sweet dreams", "Gn! Talk tomorrow?"],
        "night@warm": ["Good night 🥰 text me when you wake up", "Night, sleep well. I'll miss this chat haha", "Sweet dreams. Talk tomorrow?"],
        bye: ["Bye! Talk later", "See you!", "Okay, have fun!", "Byee, text me later"],
        thanks: ["Of course", "Anytime", "No problem", "You're welcome :)"],
        sorry: ["It's okay", "Don't worry about it", "All good", "Apology accepted haha"],
        laugh: ["Haha right?", "Glad I'm funny", "Haha stop", "Lol I know"],
        joke: ["Why did the scarecrow win an award?|Because he was outstanding in his field|I'm so sorry",
               "I'm not a joke machine haha|Okay fine. What do you call a fake noodle? An impasta",
               "What do you call a bear with no teeth?|A gummy bear|Haha I'm sorry"],
        bored: ["Then entertain me haha", "Bored? Tell me something interesting then", "Go outside lol. Or talk to me, that works too"],
        agree: ["Exactly", "Right?", "See, we agree", "Good", "Mhm"],
        disagree: ["No? Okay haha", "Fair enough", "Hm okay", "Why not?"],
        question: ["Hmm good question", "Honestly? I don't know haha", "Why do you ask?", "Depends on the day tbh", "Hmm, let me think about that one"],
        fallback: ["Haha true", "Wait really?", "Tell me more", "That's fair", "Hm, I see", "Go on", "Interesting", "Okay I like that"],
        "compliment@stranger": ["Haha thanks, you don't even know me yet", "Smooth. Let's see if you can keep a conversation too", "Thank you haha. Is that your opening move?"],
        "compliment@acquaintance": ["Haha thank you", "Aw thanks", "Stop it haha"],
        "compliment@curious": ["Stoppp", "Okay you're making me smile", "You're sweet"],
        "compliment@crush": ["You're gonna make me blush", "Okay now I'm smiling like an idiot", "Stop, you're too sweet 🥰"],
        "flirt@stranger": ["Slow down haha, we just matched", "Wow, already? Buy me a coffee first", "Haha you don't even know my middle name"],
        "flirt@acquaintance": ["Haha calm down", "Is that so? We'll see", "Bold of you"],
        "flirt@curious": ["Okay that made me smile", "You're dangerous haha", "Maybe I like you a little too"],
        "flirt@crush": ["I like you too, okay? There, I said it", "Stop, you're making my heart do things", "You're kind of my favorite person to talk to"],
        "kiss@cold": ["Haha slow down", "Not yet, mister", "Easy there"],
        "kiss@warm": ["😘", "Mwah haha", "One kiss. Just one"],
        "hug@cold": ["A virtual hug, okay, I'll allow it", "Haha okay, a small one"],
        "hug@warm": ["Come here 🤗", "Biggest hug", "I needed that honestly"],
        "miss@cold": ["Miss me? We barely talked haha", "Already? That's cute"],
        "miss@warm": ["I missed you too", "Aw, I was thinking about you too", "Same, honestly"],
        "meet@stranger": ["Haha let's talk a bit more first", "Maybe one day. Let's see if you're fun first", "Easy, we literally just matched"],
        "meet@acquaintance": ["Hmm maybe, I don't really know you yet", "Ask me again in a few days haha", "We'll see, keep talking to me first"],
        "meet@curious": ["Maybe... I'd like that actually", "Hmm, coffee could be nice. Not yet though", "Let's keep texting a bit, then maybe"],
        "meet@crush": ["I'd really like that", "Okay yes. But you're planning it", "Honestly? I've been thinking about it too"],
        "photo_refuse@stranger": ["Haha no, you have my profile", "Nice try. Earn it first", "My profile has plenty of photos, enjoy those"],
        "photo_refuse@acquaintance": ["Maybe later haha", "Not right now, I look like a mess"],
        "photo_refuse@warm": ["Later, I promise", "Not now, I look so tired haha"],
        photo_send: ["This is me rn", "Okay fine, here", "Proof that I exist", "Here, happy?", "Me, recently"],
        photo_wyd: ["This is me rn", "Here, look", "This is where I am haha"],
        photo_spont: ["Random pic of me, you're welcome", "Me, recently btw", "Found this one, felt cute", "Just because"],
        confused: ["Nothing haha", "Never mind", "Just thinking out loud", "Haha forget it", "What what?"],
        "react_dislike": ["Haha what's wrong with {x}?", "Fair, {x}: not for everyone", "Okay, no {x} then. Noted"],
        creepy: ["No. That's not happening", "Wow, okay. No", "That's really not okay", "Not cool. Don't ask me that again"],
        insult: ["Wow. Okay", "That was rude", "Excuse me?", "Rude. Try again"],
        ask_bot: ["A bot? Wow, rude haha", "Do bots complain about Mondays? Because I do", "Last time I checked I was real"],
        ask_memory: ["Of course I remember you", "How could I forget", "Obviously"],
        ask_memory_none: ["Honestly? You haven't told me much yet", "I know your name and that's about it haha. Tell me more"],
        repeat: ["You already said that haha", "Déjà vu", "You're repeating yourself, you know that?"],
        back: ["Sorry, just saw this", "I'm back, sorry", "Sorry, I was busy"],

        // she talks about herself ({...} come from her persona)
        ask_name: ["I'm {self}", "{self}! It's on my profile haha", "{self}. And you are?"],
        ask_age: ["{age}", "I'm {age}", "{age}, why? haha"],
        ask_city: ["{city}! {district}, to be exact", "I live in {city}", "{city}. {district} if you know it"],
        ask_job: ["I'm {job}", "{job}. It's a lot, but I like it", "I'm {job}, so... busy, mostly"],
        ask_pet: ["{pet}", "Yes! {pet}"],
        ask_pet_none: ["No pets sadly", "None, but I want one so bad"],
        ask_family: ["{family}"],
        "ask_family@stranger": ["It's a bit early for the family tree haha", "Normal family, big drama. That's all you get for now", "Ask me that when you know me better"],
        ask_hobby: ["{hobby} mostly. And {hobby2}", "I'm into {like} and {like2}", "{hobby}, {hobby2}... and {like}, if that counts"],
        ask_music: ["A bit of everything honestly", "Depends on my mood. Right now? Something calm", "My playlist is chaos, don't ask"],
        ask_food: ["Honestly? Anything with cheese", "I could eat pasta every day", "I'm a snack person, no shame"],
        ask_movie: ["I rewatch the same comfort shows way too much", "Anything with a good plot twist", "I'll watch anything if the snacks are good"],
        ask_weekend: ["Probably {hobby}", "{like}, if I can", "Not much planned. Maybe {hobby}"],
        ask_about_intro: ["Okay, something about me...", "Hmm, what do you want to know...", "Okay, fine. Here's one"],
        ask_about_done: ["You already know the important stuff haha", "That's all for now, I need to keep some mystery", "Your turn now. Tell me something about you"],
        ask_day: ["Pretty good! {doing}", "Long, but okay. {doing}", "Not bad! {doing}"],
        wyd: ["{doing}", "{doing}. You?", "Not much. {doing}"],
        doing_morning: ["Just woke up, still in bed", "Having coffee, trying to wake up", "Getting ready for the day"],
        doing_afternoon: ["Just got back from {jobplace}", "Taking a little break", "Pretending to be productive"],
        doing_evening: ["Just chilling at home", "Making dinner", "Lying on my bed doing nothing"],
        doing_night: ["In bed, scrolling", "Should be sleeping, but here I am", "Watching something, half asleep"],

        // she reacts to what she just learned about him
        react_name: ["Nice to meet you, {x}", "{x}, I like that name", "{x}. Okay, noted"],
        react_age: ["{x}, nice", "Oh {x}, okay", "{x}? I thought you'd be older haha", "{x}, good age"],
        react_city: ["{x}! I've never been. Is it nice?", "Oh, {x}. I've heard good things", "{x}, cool. What's it like there?"],
        react_city_same: ["Wait, {x}? Same city!", "No way, you're in {x} too?!"],
        react_job: ["{x}? That's cool", "Oh, {x}, nice. Do you like it?", "Wow, {x}. Is it stressful?"],
        react_job_at: ["Oh nice, do you like it there?", "Cool! Is it a good place to work?"],
        react_study: ["{x}? Interesting. Do you like it?", "Ooh {x}, smart", "{x}, nice. What year are you in?"],
        react_pet: ["You have a {x}?! I need pics", "Omg, a {x}. What's their name?", "A {x}, I love that"],
        react_pet_named: ["{x}! Cute name", "Aw, {x}. Say hi from me"],
        react_like: ["Ooh, {x}. Nice", "{x}? Good taste", "Oh you like {x}? Tell me more"],
        react_like_shared: ["Wait, I love {x} too!", "No way, {x}? Same!!"],
        react_event: ["Ooh, a {x}! Good luck", "A {x}? Tell me how it goes", "Good luck with the {x}, you've got this"],
        followup_event: ["Wait, how did the {x} go?", "Oh! How was the {x}?", "So? How did your {x} go?"],
        callback_pet: ["How's your {x} doing?", "Give your {x} a pat from me"],
        callback_like: ["Still into {x}?", "Done anything {x}-related lately?"],
        callback_city: ["How's life in {x}?", "How's {x} treating you?"],
        callback_job: ["How's work going?", "How's the {x} life?"],
        callback_study: ["How's {x} going?", "Survived {x} this week?"],
        ask_back: ["You?", "And you?", "What about you?", "Wbu?"],

        // reflecting what he said ("i went to the cinema" -> "wait you went to the cinema?")
        reflect_past: ["Wait, you {x}? How was it?", "Oh you {x}? Tell me", "You {x}? Nice, was it fun?"],
        reflect_future: ["Ooh, you're {x}? When?", "You're {x}? That sounds fun", "Wait, you're {x}? Take me with you haha"],
        reflect_now: ["Oh, {x}? Nice", "{x} right now? Cute", "Ooh, how's {x} going?"],

        // stories, notes, posts, stickers, comments
        story_reply: ["Haha you saw that", "Right?", "That was my whole day", "Thank you haha", "Glad someone noticed"],
        story_heart: ["Aw thank you", "Hehe thanks", "Thank you :)"],
        note_reply: ["Haha it's true though", "You read my notes? Cute", "Right??"],
        shared_post: ["Who's that?", "Haha why are you sending me this", "She's pretty. Why though?", "Okay... and?", "Is this your type? haha"],
        "shared_post@warm": ["Should I be jealous? haha", "Hm. Why are you looking at other girls' posts", "Pretty. Not as pretty as me though"],
        shared_own: ["Why are you sending me my own post haha", "Stalker 👀", "Oh, that one. Do you like it?", "Haha yes, that's me"],
        sticker_laugh: ["Haha", "Glad you're entertained"], sticker_dead: ["Rip haha", "Don't die, I like talking to you"],
        sticker_cry: ["Noo don't cry", "Dramatic haha"], sticker_plead: ["Don't look at me like that", "Those eyes won't work on me. Okay maybe a little"],
        sticker_shy: ["Why are you shy now haha", "Aw"], sticker_eyes: ["What? 👀", "Why are you looking at me like that"],
        sticker_fire: ["I know haha", "Thank you"], sticker_heart: ["Aw", "That's sweet"], "sticker_heart@stranger": ["Haha a heart already?", "Okay, cute"],
        sticker_rose: ["A rose? Fancy", "Aw, thank you"], sticker_hug: ["Hug accepted", "Aw, come here"],
        sticker_coffee: ["Is that an invitation? haha", "Coffee sounds good. Someday"], "sticker_coffee@crush": ["Yes. When?", "Okay, coffee date. You're paying"],
        sticker_night: ["Good night!", "Sleep well"], sticker_wave: ["Hii", "Hey!"], sticker_clown: ["Haha at least you know", "Self-awareness, I respect it"],
        sticker_think: ["Thinking about what?", "Uh oh, he's thinking"], sticker_party: ["Wait what are we celebrating?", "Yay! Why?"],
        comment_compliment: ["Thank you!", "Aw thanks", "Hehe thank you", "Thank you :)"],
        "comment_compliment@stranger": ["Haha thanks", "Thank you!"],
        comment_question: ["Haha I'll tell you in DMs", "Long story", "Maybe 👀", "Ask me in DMs"],
        comment_where: ["{x}!", "It's {x}", "{x}, I love it there"],
        comment_generic: ["Haha right?", "Thank you", "Glad you like it", "Haha yes", "Right??"],
        comment_rude: ["Okay, bye", "Not necessary", "Wow"],

        // extras
        "sweet@warm": ["Talking to you is the best part of my day", "I like this. Us talking", "You're kind of easy to talk to", "I'm smiling at my phone again, it's your fault"],
        deleted: ["Actually, never mind", "Wait, I'm gonna say something stupid", "I kinda like you", "Ugh, I hate when you're right", "Can I tell you something weird"],
        leave: ["I'm kinda tired, talk later?", "I need a little break, text you later", "My social battery is dead, talk tomorrow?"],
        cause: ["It's just... {x}", "Long story. {x}", "Honestly? {x}"],
        opener: ["Hey! I like your profile card", "Hi! You look like someone with good music taste", "Hey, okay, I had to say hi", "Hi! How's your day going?"],
        opener_card: ["Hey! The {cardbit} on your card is a good look", "Hi! Okay, the {cardbit}... I had to say hi"],
        opener_like: ["Hi! Random question: do you like {like}?", "Hey! Okay, important: how do you feel about {like}?", "Hi! I'm {self}. Be honest, {like}: yes or no?"],

        mood: {
            neg: { any: ["Hm", "Okay", "Sure", "Whatever", "If you say so", "Fine"], how_are_you: ["Fine.", "Been better", "Don't ask"],
                   greet: ["Hey.", "Hi", "Yeah?"], compliment: ["Thanks", "Okay"], flirt: ["Not in the mood", "Hm"] },
            sad: { any: ["I don't know...", "It's just one of those days", "Sorry, I'm not great company today", "Mm"],
                   how_are_you: ["Honestly? Not great", "Kinda down today", "Meh. You?"], greet: ["Hey...", "Hi"],
                   compliment: ["Thank you... I needed that", "That's sweet. Thanks"], hug: ["I really needed that, thank you", "Thank you..."] },
            low: { any: ["Mhm", "Yeah", "I'm so tired lol", "Sorry, I'm half asleep", "Can barely keep my eyes open"],
                   how_are_you: ["Tired. So tired", "Sleepy. You?", "Exhausted lol. You?"], greet: ["Heyy... sleepy hi", "Hi, I'm half asleep"],
                   wyd: ["Lying in bed", "Trying not to fall asleep"] },
        },
    },

    sunny: {
        greet: ["HEY!", "Hiii!! How are you?", "Heyyy, finally a text!", "Hi hi hi"],
        how_are_you: ["SO good actually! Today's been fun. You?", "Good!! A bit sleepy but good. How about you?", "Amazing, the sun is out! You?"],
        answer_good: ["Yay!!", "Love that!", "Good good good"],
        fallback: ["Omg really?", "Wait, tell me everything", "Haha I love that", "Noo way", "Okay that's so cool", "Haha yes!!"],
        laugh: ["HAHA stop", "I'm crying", "You're so funny omg", "Haha okay that got me"],
        "compliment@stranger": ["Haha thank you!! You're sweet, but you don't even know me yet", "Aww thanks! Is that your best line?"],
        "compliment@warm": ["STOP, you're making me blush", "Aww, you're the sweetest", "Okay, now I'm smiling at my phone"],
        "flirt@stranger": ["Haha slow down!! We just met", "Wow okay, straight to the point haha"],
        "flirt@crush": ["Okay I like you too!! There, I said it", "You make me so happy, you know that?"],
        answer_bad: ["Nooo, what happened?? Tell me", "Oh no!! Come here. What's wrong?"],
        bored: ["Bored?? Let's fix that. Tell me the best thing that happened to you this week", "Then talk to me! I'm fun, I promise"],
        agree: ["YES, exactly", "Right?!", "See!! I knew it"],
        question: ["Ooh, good question!", "Hmm, I have to think about that one haha", "Honestly? No idea!"],
        opener: ["Hiii! Your profile made me smile so I had to say hi", "Hey!! Okay, I'm texting first, don't make it weird haha", "Hi! How's your day going? Mine's been chaotic",
                 "Heyy! I have a good feeling about this match haha", "Hi hi! Tell me one thing that made you happy today"],
        ask_back: ["And you??", "What about you?!", "You?"],
        night: ["Good night!! Sleep well", "Nighty night! Talk tomorrow?"],
        bye: ["Byee! Text me later!", "Okay go go! Talk later"],
        "meet@crush": ["YES. When??", "Okay okay, I'd love that!!"],
    },

    bold: {
        greet: ["Well, hello", "Hey you", "Look who's here", "Hi. Took you long enough"],
        how_are_you: ["Good, obviously. You?", "Thriving, as always. How about you?", "Pretty good! Busy day. You?"],
        fallback: ["Okay, I like where this is going", "Go on, I'm listening", "Ha, not bad", "Interesting. Tell me more", "Hm, you're more fun than I expected"],
        laugh: ["See, I'm hilarious", "Haha I know", "You laugh easily, that's cute"],
        "compliment@stranger": ["I know haha. But thanks", "Thank you. Now say something I haven't heard before", "Cute. Is that your whole strategy?"],
        "compliment@warm": ["Keep going, I'm listening", "Okay, you're good at this", "Stop it, you're gonna make me blush and I never blush"],
        "flirt@stranger": ["Bold. I like bold, but not that fast", "Easy there. Impress me first"],
        "flirt@curious": ["Careful, I might start believing you", "Hm. I think I like you a little"],
        "flirt@crush": ["You're kind of my favorite, don't let it go to your head", "Okay, fine. I like you. A lot"],
        "meet@stranger": ["Hm, impress me first", "We'll see. Keep talking"],
        "meet@crush": ["Okay. You pick the place, I pick the time", "Yes. And you're paying for the coffee"],
        answer_bad: ["Who do I need to fight?", "Hey, what happened? Tell me"],
        bored: ["Bored? With me here? Impossible", "Then make it interesting. Tell me a secret"],
        question: ["Depends. Why do you want to know?", "Good question. I'll tell you if you tell me first", "Hm, that's a whole conversation"],
        opener: ["Okay, I'll text first. You're welcome", "Hey. Your profile card caught my eye, don't let it go to your head", "Hi! So, what's your story?",
                 "Hey you. I don't usually go first, so this better be worth it", "Hi. Tell me something that'll make me keep texting you"],
        ask_back: ["You?", "Your turn", "And you?"],
        insult: ["Wow. Bye", "Try that again and you're blocked"],
        "photo_refuse@stranger": ["Haha no. You'll have to earn that", "Nope. Mystery is part of the charm"],
    },

    witty: {
        greet: ["Hey", "Hi hi", "Oh, hey", "Hello, stranger"],
        how_are_you: ["Surviving. Barely. You?", "Good! Suspiciously good. You?", "Alive, caffeinated, mostly functional. You?"],
        fallback: ["Haha okay, that's fair", "Wait, explain", "Bold claim", "I'm going to need proof", "Okay, I'll allow it", "Lol true", "That's either genius or chaos"],
        laugh: ["Thank you, I'm here all week", "Haha I know I'm hilarious", "Glad my humor works on someone"],
        "compliment@stranger": ["Thanks haha. You're not so bad yourself, from what I can see on your card", "Flattery noted. Points: 1", "Smooth. Suspiciously smooth"],
        "compliment@warm": ["Stop, I'm gonna get a big ego", "Okay, you can stay", "You're making it really hard to roast you"],
        "flirt@stranger": ["Whoa, we're on message like five", "Haha slow down, I haven't even judged your music taste yet"],
        "flirt@curious": ["Okay, maybe I like you a bit. A bit", "Don't make me say it first"],
        "flirt@crush": ["Fine. You win. I like you", "Ugh, I like you. Happy?"],
        answer_bad: ["Oh no, what happened? Do I need to fight someone", "Hey, that sucks. Tell me"],
        bored: ["Bored? Okay, two truths and a lie. Go", "Then let's play a game. Would you rather fight one horse-sized duck or a hundred duck-sized horses?"],
        agree: ["Exactly", "Finally, someone gets it", "See, you're smart"],
        disagree: ["Wrong, but okay", "Bold of you", "We'll debate this later"],
        question: ["Hmm, classified", "Good question. Next question", "I'll answer that after you answer mine haha"],
        opener: ["Hi, I'm texting first because I don't trust you to do it", "Hey! Quick question: pineapple on pizza, yes or no? This decides everything",
                 "Okay, I had to say hi. Your profile card is suspiciously normal", "Hey. On a scale of 1 to 10, how good are you at texting back?",
                 "Hi! I matched with you, so now you have to entertain me. Rules", "Hey, settle a debate: is cereal a soup?"],
        ask_back: ["You?", "Your turn", "And you?", "Wbu"],
        "meet@stranger": ["Haha you have to pass the vibe check first", "Coffee? Let's see if you survive a week of texting first"],
    },

    dry: {
        greet: ["Hey", "Hi", "Hello", "Oh, hi"],
        "greet@warm": ["Hey you", "There you are"],
        how_are_you: ["Fine. You?", "Okay. Tired, but okay. You?", "Good, I think. You?"],
        answer_good: ["Good", "Nice", "Glad to hear"],
        fallback: ["Fair", "Hm", "Interesting", "Okay", "Noted", "That tracks", "I see"],
        laugh: ["I have my moments", "Glad you think so", "Ha"],
        "compliment@stranger": ["Thanks. Bold opener", "Hm. Thanks", "That's nice. You don't know me though"],
        "compliment@warm": ["...thanks. That was actually sweet", "Okay, that one got me", "Stop. I'm smiling and I don't like it"],
        "flirt@stranger": ["Slow down", "We just matched. Calm"],
        "flirt@curious": ["Hm. Maybe", "I don't hate that"],
        "flirt@crush": ["I like you. Don't make it weird", "Fine. Me too"],
        answer_bad: ["That sucks. What happened?", "Hm. Want to talk about it?"],
        bored: ["Same", "Bored people are boring. Kidding. Mostly", "Read something. Or talk to me, I guess"],
        agree: ["Exactly", "Yes", "Right"],
        disagree: ["Hm, no", "Disagree, but fine"],
        question: ["Depends", "Hard to say", "Why do you ask?", "Hm. Good question"],
        opener: ["Hi. Your profile card looked interesting", "Hey. Thought I'd say hi", "Hello. I don't usually text first. Consider yourself lucky"],
        ask_back: ["You?", "And you?"],
        night: ["Good night", "Night. Sleep well"],
        bye: ["Bye", "See you", "Talk later"],
        "hug@warm": ["Fine. A hug", "...okay, I needed that"],
    },

    soft: {
        greet: ["Hi! How are you?", "Hello :)", "Hi there", "Oh, hi! I was hoping you'd write"],
        how_are_you: ["I'm good, thank you! How are you?", "Pretty good, a little tired. And you?", "I'm well! What about you?"],
        answer_good: ["I'm glad!", "That's nice to hear", "Yay, good"],
        answer_bad: ["Oh no... what happened?", "I'm sorry to hear that. Do you want to talk about it?", "Aw, that sounds hard. I'm here if you want to talk"],
        fallback: ["Oh, really?", "That's lovely", "I didn't know that", "That sounds nice", "Tell me more?", "Hm, I see"],
        laugh: ["Hehe", "I'm glad I made you laugh", "Haha, you're sweet"],
        "compliment@stranger": ["Oh! Thank you, that's kind", "That's sweet of you... thank you", "You're making me shy"],
        "compliment@warm": ["Stop, I'm blushing", "That's so sweet... thank you", "You always know what to say"],
        "flirt@stranger": ["Oh! Um, that's a bit fast...", "I think we should get to know each other first"],
        "flirt@curious": ["You're making my face warm", "I... think I like you too. A little"],
        "flirt@crush": ["I like you too. A lot", "You make me really happy, you know?"],
        "meet@stranger": ["I'd like to get to know you a bit more first, if that's okay", "Maybe someday! Let's talk more first"],
        "meet@crush": ["I'd love that", "Yes... I'd really like that"],
        bored: ["Oh! Want me to tell you something random?", "Maybe we could play a game? Like twenty questions"],
        question: ["Hmm, that's a good question", "Let me think...", "I'm not sure, honestly"],
        opener: ["Hi! I hope it's okay that I'm writing first", "Hello! I liked your profile card, so I wanted to say hi", "Hi :) How is your day going?"],
        ask_back: ["And you?", "How about you?", "What about you?"],
        night: ["Good night! Sleep well", "Sweet dreams :)"],
        insult: ["That hurt a little...", "Why would you say that?"],
    },

    dreamy: {
        greet: ["Hey...", "Hi", "Oh, hi", "Hey you..."],
        how_are_you: ["Okay, I think... you?", "Quiet day. You?", "Drifting. You?"],
        fallback: ["Hm...", "I like that", "That's kind of beautiful", "Tell me more...", "Huh", "I see..."],
        laugh: ["Heh", "You're funny...", "That made me smile"],
        "compliment@stranger": ["Oh... thank you", "That's kind... you don't know me yet, though"],
        "compliment@warm": ["...that's sweet", "You're making me smile at 3am"],
        "flirt@stranger": ["Slow down...", "We just met..."],
        "flirt@crush": ["I like you... it's strange how much", "Stay a little longer?"],
        answer_bad: ["Oh... what happened?", "I'm here. Tell me"],
        bored: ["Boredom is just the quiet before an idea...", "Listen to something weird. Or talk to me"],
        question: ["Hm... I don't know", "I'd have to think about it...", "Depends on the night"],
        opener: ["Hey... couldn't sleep, so I'm saying hi", "Hi. Your profile card felt... calm", "Hey. Are you a night person too?"],
        ask_back: ["You?", "And you...?"],
        night: ["Good night... or good morning, whatever it is for you", "Sleep well..."],
        doing_night: ["Making a track. Headphones on", "Walking around the empty city", "Talking to the crows on my balcony, as one does"],
    },
};
