// js/local/dialog/topics.js - What the message is about (like Amor's topics.js).
// The intent says what kind of message it is, the topic what it's about:
// "the match yesterday was awful" -> football + bad news. A topic stays on her mind for a few
// messages, so "it was so bad" still counts as football. Lines per tone:
//     good / bad (his news), ask (a question about it), any (just mentioned), cont (the topic goes on),
//     love / meh (her taste: it's in her likes / dislikes - "tastes" are matched against her persona)
window.SL = window.SL || {};
SL.dialog = SL.dialog || {};

SL.dialog.TONES = {
    good: ["great", "amazing", "awesome", "won", "win", "passed", "fun", "love", "loved", "best", "happy", "finally", "nice", "so good", "perfect", "incredible", "excited", "can't wait", "cant wait", "fantastic", "beautiful", "delicious", "got the job", "got in"],
    bad: ["bad", "terrible", "awful", "failed", "fail", "lost", "lose", "sucks", "sucked", "worst", "hate", "tired", "sick", "annoying", "boring", "stressful", "stressed", "broke", "ugh", "disaster", "horrible", "hurt", "cancelled", "canceled", "rained", "rejected", "didn't get", "not good", "so hard"],
    close: ["anyway", "nevermind", "never mind", "forget it", "doesn't matter", "whatever", "moving on"],
};

SL.dialog.TOPICS = [
    { id: "music", words: ["music", "song", "songs", "playlist", "album", "concert", "spotify", "band", "singer", "rapper", "listening to", "headphones", "guitar", "piano", "festival"],
      tastes: ["music", "song", "playlist", "concert", "rap", "jazz", "pop", "rock", "indie", "piano", "guitar", "vinyl", "techno", "city pop", "darkwave", "ukulele", "synth"],
      lines: { good: ["That sounds amazing!", "Okay now I want to hear it"], bad: ["Oh no, what happened?", "That sucks, music is supposed to be the fun part"],
               ask: ["Honestly, a bit of everything", "Depends on my mood haha"], any: ["What are you listening to these days?", "Ooh, send me a song"],
               love: ["Music is my whole personality, honestly", "Okay you just found my favorite topic"], meh: ["I'm not much of a music person, don't judge"],
               cont: ["Okay, you're really into music huh", "Send me your top song right now"] } },
    { id: "movies", words: ["movie", "movies", "film", "films", "cinema", "netflix", "series", "episode", "season", "show", "watched", "watching", "anime", "trailer"],
      tastes: ["movie", "film", "cinema", "series", "horror", "netflix", "anime", "drama", "ghibli", "suits", "k-drama", "show"],
      lines: { good: ["Ooh, now I need to watch it", "Okay, adding it to my list"], bad: ["Haha that bad?", "Wasted two hours, rip"],
               ask: ["Anything with a good twist", "I rewatch my comfort shows way too much"], any: ["What was it about?", "Is it worth watching?"],
               love: ["Okay, I love talking about films", "Movie nights are my thing honestly"], meh: ["I fall asleep during most movies, it's a problem"],
               cont: ["You watch a lot, huh. I like that", "Okay, give me your top three"] } },
    { id: "food", words: ["food", "eat", "ate", "eating", "dinner", "lunch", "breakfast", "pizza", "burger", "sushi", "pasta", "cooking", "cooked", "restaurant", "hungry", "snack", "dessert", "cake", "kebab", "ramen"],
      tastes: ["food", "pasta", "sushi", "ramen", "pizza", "cake", "baking", "cooking", "dessert", "mantı", "iskender", "börek", "boyoz", "fries", "bun", "tapas", "breakfast", "hellim", "freddo"],
      lines: { good: ["Okay now I'm hungry", "That sounds so good"], bad: ["Noo, bad food is a tragedy", "Haha what went wrong?"],
               ask: ["Anything with cheese, honestly", "Today? Too much coffee and not enough food haha"], any: ["Did you cook it yourself?", "What did you have?"],
               love: ["Food is my love language", "You can't talk about food with me, I get too excited"], meh: ["I'm a picky eater, it's embarrassing"],
               cont: ["We keep talking about food, are you hungry?", "Okay, you're a food guy, I see"] } },
    { id: "coffee", words: ["coffee", "espresso", "latte", "cappuccino", "starbucks", "caffeine", "tea", "matcha", "chai"],
      tastes: ["coffee", "espresso", "latte", "tea", "matcha", "café", "cafe", "freddo"],
      lines: { good: ["Good coffee fixes everything", "A good coffee is a good day"], bad: ["Bad coffee is a crime", "Noo, that ruins the whole day"],
               ask: ["Too much coffee, honestly", "Iced, always iced"], any: ["How do you take it?", "Coffee or tea person?"],
               love: ["Coffee is my personality", "I'd marry coffee if I could"], meh: ["I'm more of a tea girl"],
               cont: ["You and coffee, a love story", "Okay, how many cups today?"] } },
    { id: "sport", words: ["gym", "workout", "work out", "run", "running", "ran", "training", "exercise", "yoga", "pilates", "swim", "swimming", "lift", "lifting", "marathon", "hike", "hiking", "bike", "cycling", "tennis", "basketball", "volleyball"],
      tastes: ["gym", "yoga", "pilates", "run", "parkrun", "swim", "swimming", "hike", "surf", "skiing", "sailing", "cycling", "tennis", "sport", "dance", "salsa"],
      lines: { good: ["Look at you, so disciplined", "Nice! That's impressive"], bad: ["Ouch, are you okay?", "Rest day then haha"],
               ask: ["I try. Some weeks better than others haha", "Does walking to the fridge count?"], any: ["Do you go often?", "Wow, sporty"],
               love: ["Okay, a sporty one, I love that", "Same, I'd go crazy without moving"], meh: ["I respect it, but I'm a couch person"],
               cont: ["You're really into this huh", "Okay, gym guy confirmed"] } },
    { id: "football", words: ["football", "soccer", "match", "goal", "league", "team", "fenerbahce", "galatasaray", "besiktas", "barca", "real madrid", "premier league", "champions league", "world cup", "f1", "formula 1", "race", "nba"],
      tastes: ["football", "f1", "formula 1", "racing", "soccer", "basketball"],
      lines: { good: ["Yesss, good game then!", "Haha you must be happy"], bad: ["Oof. Sorry for your team haha", "Ah, sports heartbreak"],
               ask: ["I watch the big games, that's it", "Honestly I just watch for the snacks"], any: ["Which team are you?", "Do you play too or just watch?"],
               love: ["Okay, I'm actually really into this", "Don't get me started, I'll talk for hours"], meh: ["I don't really get football, sorry haha"],
               cont: ["Okay, you really love your team", "This is a whole thing for you, huh"] } },
    { id: "games", words: ["game", "games", "gaming", "playstation", "ps5", "xbox", "nintendo", "switch", "steam", "valorant", "league of legends", "fortnite", "minecraft", "elden ring", "stardew", "controller", "gamer"],
      tastes: ["game", "games", "gaming", "stardew", "elden ring", "baldur", "board game", "nintendo"],
      lines: { good: ["Gamer win!", "Nice, gg"], bad: ["Rage quit?", "Haha, it happens to the best of us"],
               ask: ["Sometimes! Cozy games mostly", "I'm terrible, but I try"], any: ["What do you play?", "Are you any good though?"],
               love: ["Okay wait, you game too?", "Finally someone I can talk games with"], meh: ["I'm hopeless at games honestly"],
               cont: ["Okay, gamer confirmed", "How many hours do you have in that, be honest"] } },
    { id: "travel", words: ["travel", "trip", "vacation", "holiday", "flight", "airport", "beach", "abroad", "visit", "visited", "traveling", "travelling", "passport", "hotel", "road trip"],
      tastes: ["travel", "trip", "travelling", "traveling", "road trip", "beach", "sea", "islands", "backpack", "kyoto", "valencia"],
      lines: { good: ["Ooh, where to?", "That sounds amazing, I'm jealous"], bad: ["Oh no, travel stress is the worst", "What happened?"],
               ask: ["I'd go anywhere with a sea", "I want to go everywhere, honestly"], any: ["Where would you go if you could?", "Do you travel a lot?"],
               love: ["Travel is my favorite thing in the world", "Okay, now I want to pack a bag"], meh: ["I'm more of a homebody, honestly"],
               cont: ["Okay, you really love traveling", "Tell me your best trip ever"] } },
    { id: "work", words: ["work", "job", "boss", "office", "shift", "meeting", "colleague", "coworker", "deadline", "overtime", "salary", "promotion", "interview", "clients", "project"],
      tastes: ["work", "job", "design", "studio", "firm", "office"],
      lines: { good: ["Look at you! Congrats", "Yes, that's amazing"], bad: ["Work is the worst sometimes", "Ugh, that sounds exhausting"],
               ask: ["Busy, but okay", "Work is work haha"], any: ["Do you like your job?", "Long day?"],
               love: ["I actually love my work, is that weird?"], meh: ["Don't make me think about work haha"],
               cont: ["Your job sounds intense", "Okay, no more work talk, you need a break"] } },
    { id: "study", words: ["exam", "exams", "test", "class", "classes", "lecture", "uni", "university", "college", "school", "homework", "assignment", "thesis", "professor", "studying", "study", "grades", "finals", "semester"],
      tastes: ["study", "uni", "university", "exam", "library", "class"],
      lines: { good: ["Yesss, congrats!!", "See, you're smart"], bad: ["Ugh, exams are the worst", "Noo, that's so stressful"],
               ask: ["Don't remind me haha", "Surviving, barely"], any: ["What are you studying?", "When's the exam?"],
               love: ["Okay, I'm a bit of a nerd, I like that stuff"], meh: ["School stress, I know it too well"],
               cont: ["You really have a lot on your plate", "Take a break, you deserve it"] } },
    { id: "weather", words: ["weather", "rain", "raining", "rainy", "snow", "snowing", "sunny", "cold", "freezing", "hot today", "so hot", "heat", "storm", "windy", "cloudy"],
      tastes: ["rain", "snow", "sun", "winter", "summer", "rainy days"],
      lines: { good: ["Perfect weather is everything", "Lucky, enjoy it"], bad: ["Ugh, same here", "Stay inside and stay warm"],
               ask: ["Cold, but okay", "It changes every five minutes here"], any: ["What's the weather like there?", "Here it's the same, honestly"],
               love: ["I love that kind of weather", "That's my favorite weather!"], meh: ["I hate that kind of weather"],
               cont: ["We're talking about the weather, are we old now haha"] } },
    { id: "pets", words: ["cat", "cats", "dog", "dogs", "puppy", "kitten", "pet", "pets", "hamster", "bird", "rabbit", "vet", "my cat", "my dog"],
      tastes: ["cat", "cats", "dog", "dogs", "animals", "pets", "animal"],
      lines: { good: ["Aww, that's so cute", "I need a photo of that immediately"], bad: ["Oh no, is everything okay?", "Poor baby"],
               ask: ["I love animals", "Cats, always"], any: ["Do you have one?", "What's their name?"],
               love: ["Animals are my weakness", "Okay, you just made my day"], meh: ["I'm a bit scared of animals, don't laugh"],
               cont: ["Okay, more pet stories please", "You're an animal person, I can tell"] } },
    { id: "sleep", words: ["sleep", "sleeping", "slept", "insomnia", "nap", "tired", "exhausted", "awake", "can't sleep", "cant sleep", "bed", "alarm", "woke up"],
      tastes: ["sleep", "naps", "nap"],
      lines: { good: ["A good sleep fixes everything", "Lucky, I'm jealous"], bad: ["Go to sleep! Seriously", "Noo, you need rest"],
               ask: ["Not enough, honestly", "Like a baby. A baby who wakes up at 3am"], any: ["Did you sleep well?", "Same, I'm so sleepy"],
               love: ["Naps are sacred", "Sleep is my favorite hobby"], meh: ["I barely sleep, it's a problem"],
               cont: ["Okay, you really need some sleep"] } },
    { id: "party", words: ["party", "partying", "club", "clubbing", "drinks", "drinking", "bar", "night out", "drunk", "hangover", "hungover", "birthday party", "wedding"],
      tastes: ["party", "parties", "club", "night out", "drinks", "rooftop", "karaoke", "wedding"],
      lines: { good: ["Okay party animal", "Sounds like a fun night"], bad: ["Hangover? Water and sleep", "Haha, rough night?"],
               ask: ["Sometimes! I'm more of a small-group person", "Depends on the people"], any: ["Where did you go?", "Was it fun?"],
               love: ["Okay, I love a good night out", "Take me next time haha"], meh: ["I'm more of a stay-home-with-tea person"],
               cont: ["You go out a lot, huh", "Okay, tell me the craziest part"] } },
    { id: "books", words: ["book", "books", "reading", "read", "novel", "author", "library", "kindle", "chapter"],
      tastes: ["book", "books", "reading", "novel", "library", "poetry", "kanji"],
      lines: { good: ["Ooh, what's it called?", "I love a good book"], bad: ["Haha, not every book is a winner", "DNF it, life's too short"],
               ask: ["When I have time, yes", "I'm a slow reader, but I love it"], any: ["What are you reading?", "Is it good?"],
               love: ["Okay, a reader. Instant points", "Books are my safe place"], meh: ["I'm not much of a reader honestly"],
               cont: ["Okay, you really love books, I like that"] } },
    { id: "art", words: ["art", "drawing", "draw", "painting", "paint", "museum", "gallery", "design", "sketch", "photography", "photo shoot", "camera", "tattoo"],
      tastes: ["art", "drawing", "painting", "museum", "design", "sketch", "photography", "film photography", "tattoo", "illustration", "calligraphy", "fonts"],
      lines: { good: ["That's so cool!", "I'd love to see it"], bad: ["Creative blocks are the worst", "Aw, it happens"],
               ask: ["I love art, even if I'm not great at it", "I doodle a lot haha"], any: ["Do you make art too?", "Show me sometime?"],
               love: ["Okay, now you're speaking my language", "Art is my whole world honestly"], meh: ["I'm not very artsy, but I like looking"],
               cont: ["You're an artsy one, I see"] } },
    { id: "sea", words: ["sea", "beach", "ocean", "swim", "surf", "surfing", "waves", "sunset", "boat", "island", "coast"],
      tastes: ["sea", "beach", "ocean", "surf", "sunset", "swimming", "boat", "aegean", "kordon", "bosphorus", "coast"],
      lines: { good: ["Okay, that's my dream day", "The sea always wins"], bad: ["Aw, the sea will be there next time"],
               ask: ["Always. I need to be near water", "The beach is my happy place"], any: ["Do you live near the sea?", "Beach or pool?"],
               love: ["You just said the magic word", "The sea is my favorite place in the world"], meh: ["I burn in like five minutes, so..."],
               cont: ["Okay, now I miss the sea"] } },
    { id: "fashion", words: ["outfit", "clothes", "shopping", "fashion", "dress", "shoes", "sneakers", "jacket", "style", "vintage", "thrift", "makeup", "hair"],
      tastes: ["fashion", "vintage", "outfit", "makeup", "clothes", "shopping", "y2k", "style", "jewelry", "lipstick", "hair"],
      lines: { good: ["Ooh, show me", "Love that for you"], bad: ["Fashion emergency?", "Haha, it happens"],
               ask: ["I love a good outfit", "Too much, ask my bank account"], any: ["What did you get?", "What's your style?"],
               love: ["Okay, I could talk about this forever", "Fashion is my thing, careful"], meh: ["I just wear whatever is clean haha"],
               cont: ["You care about style, I like that"] } },
    { id: "family", words: ["mom", "mum", "dad", "parents", "brother", "sister", "family", "grandma", "grandpa", "cousin", "aunt", "uncle", "nephew", "niece"],
      tastes: ["family", "niece", "sister", "brother", "grandma"],
      lines: { good: ["Aw, that's so sweet", "Family time is the best"], bad: ["Family stuff is hard sometimes", "I'm sorry, that sounds rough"],
               ask: ["They're loud, but I love them", "Family is everything"], any: ["Are you close with them?", "Do you see them a lot?"],
               love: ["I'm a family person, honestly"], meh: ["Family is... complicated haha"],
               cont: ["You talk about them a lot, you must be close"] } },
    { id: "friends", words: ["friend", "friends", "bestie", "best friend", "roommate", "flatmate", "group chat", "the boys", "the girls", "buddy"],
      tastes: ["friends", "best friend", "roommate"],
      lines: { good: ["Good friends are everything", "Haha sounds fun"], bad: ["Friend drama is the worst", "Oof, what happened?"],
               ask: ["A few, but they're the best", "My friends are chaos"], any: ["Are you close?", "Haha, tell me about them"],
               cont: ["Your friends sound like a lot of fun"] } },
    { id: "health", words: ["sick", "ill", "fever", "cold", "flu", "headache", "doctor", "hospital", "pain", "hurt", "injury", "covid", "allergy"],
      tastes: ["health", "nursing", "hospital"],
      lines: { good: ["Good, glad you're feeling better", "Yay, healthy again"], bad: ["Oh no, get some rest", "Drink water and sleep, okay?"],
               ask: ["I'm okay, just tired", "Healthy-ish haha"], any: ["Are you okay?", "Take care of yourself"],
               cont: ["Are you feeling any better?"] } },
];

// shared taste lines when a topic has none of its own
SL.dialog.TOPIC_SHARED = {
    love: ["Wait, I love that!", "Okay, you have my attention", "Ooh, that's one of my favorite things"],
    meh: ["Hm, not really my thing", "Each to their own haha", "I don't really get it, but okay"],
};
